### ISSUE TITLE
[Bug/Feature] Gradle 8.0 incompatibility

### ISSUE THREAD

**Issue by chbussler** [temporalio/money-transfer-project-template-java#17]
### What are you really trying to do?

- Newbie installing and running this tutorial

### Describe the bug

- See attached screenshots; these error messages appear during project build as well as workflow execution
- Not sure if this is a bug, could be a feature request as well

### Minimal Reproduction

- Install and run from scratch

### Environment/Versions
- OS and processor:  x86 Windows 11 Pro
- IntelliJ 2022.1.13
- Java JDK 18.0.1

### Additional context
- (1)
![Screenshot 2022-06-26 180623](https://user-images.githubusercontent.com/845247/175848249-f7759cb2-f12c-4d2f-9d3e-d029790d5436.png)

- (2)
![Screenshot 2022-06-26 181258](https://user-images.githubusercontent.com/845247/175848279-8a6f834a-831a-4bb9-a987-254ac18a41c4.png)

- (3)
![Screenshot 2022-06-26 180907](https://user-images.githubusercontent.com/845247/175848301-f2e9094b-c7ce-4987-91b8-d8dba64da3dd.png)

**Comment by efortuna** [comment]
Fixed with https://github.com/temporalio/money-transfer-project-template-java/pull/19
